# Generated by Django 4.2.6 on 2023-10-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_is_read_remove_message_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='room',
            field=models.UUIDField(auto_created=True, editable=False, null=True, unique=True),
        ),
    ]
