# Generated by Django 4.2.6 on 2023-10-30 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_conversation_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='room',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
