# Generated by Django 4.2.6 on 2023-10-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
