# Generated by Django 4.2.7 on 2023-11-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_storymedia_remove_storyvideo_user_delete_storyimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='stories/'),
        ),
    ]
