# Generated by Django 4.2.6 on 2023-10-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_alter_user_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='interest',
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.ManyToManyField(blank=True, related_name='users', to='userauth.interest'),
        ),
    ]
