# Generated by Django 4.2.7 on 2023-11-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='open_to_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
